services:
  - docker

env:
  global:
    SHA=$(git rev-parse --short HEAD)

jobs:
  include:
    - stage: Test
      script:
      - npm test
    - stage: Build & Push
      script:
      - echo "Build stage"
      - sed -i -e "s/SHA_COMMIT/${SHA}/" git-commit.json
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t tech-challenge-01 .
      - docker images
      - docker tag tech-challenge-01 $DOCKER_USERNAME/tech-challenge-01
      - docker push $DOCKER_USERNAME/tech-challenge-01
